// React/app-1/src/components/posts/FullPostComponent.js
import React, { Component } from "react";
import "./post.css";

class FullPostComponent extends Component {
  render() {
    let { item } = this.props;
    return (
      <div className="post_full">
        POST - {item.id} - by user - {item.userId}
        <h3>{item.title}</h3>
        <p className="post_text">{item.body}</p>
      </div>
    );
  }
}

export default FullPostComponent;

// Angular/src/app/components/full-post/full-post.component.ts
import {Component, Input, OnInit} from '@angular/core';
import {Post} from '../../../models/Post';

@Component({
  selector: 'app-full-post',
  templateUrl: './full-post.component.html',
  styleUrls: ['./full-post.component.css']
})
export class FullPostComponent implements OnInit {
  @Input()
  post: Post;

  constructor() { }

  ngOnInit(): void {
  }

}

<div class="info">
  <h3>Title: {{post?.title}}</h3>
  <h5>Post ID: {{post?.id}}, User ID: {{post?.userId}}</h5>
  <p>Body: {{post?.body}}</p>
</div>
